### ISSUE TITLE
The remote name could not be resolved

### ISSUE THREAD

**Issue by glalwani2** [Azure-Samples/SpeechToText-REST#1]
![image](https://user-images.githubusercontent.com/14043531/31577985-05dac836-b136-11e7-9710-e84acb8d864d.png)

I am trying to run the code samples for both windows and rest and its not working. Some how the token end point is not working even with a valid subscription key. It only generated the token first time yesterday and after that even if I am trying with different code samples and key, the token issue endpoint is not returning.I tried a rest client as well nothing is returned as such, Please look into it.

**Comment by zhouwangzw** [comment]
Thanks for reporting the issue. We are looking into it. As work around, would it be possible for you to directly use Subscription, instead of Authorization token, as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedrest?tabs=Powershell)?

**Comment by zhouwangzw** [comment]
@glalwani2 Do you still have the problem? I have use both Windows and REST using Authorization token. If you are using free trial key, please double check whether your key is expired or exceeds the quota.

**Comment by zhouwangzw** [comment]
I am closing the issue. If you still have problem or questions, please feel free to reopen a new one.
