### ISSUE TITLE
request.getResponse returned 501 error.

### ISSUE THREAD

**Issue by ravigav** [Azure-Samples/SpeechToText-REST#2]
tried to invoke a speech to text api. By invoking the uri : https://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?language=pt-BR
passed a wav file as an input. 
When called request.GetResponse(). gave an exception "remote server returned an error : 501. Not implemented"

**Comment by wolfma61** [comment]
The documentation for the REST API is here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedrest

The sample on that page is working, assuming you are supplying correct parameters (keys, wave file format etc).

Wolfgang

**Comment by zhouwangzw** [comment]
I am closing the issue due to lack of response. Please open a  new one if you still have issues.
