### ISSUE TITLE
Files outdated?

### ISSUE THREAD

**Issue by elig0n** [Azure-Samples/SpeechToText-REST#5]
It seems almost everything is outdated as the BING API has changed

**Comment by zhouwangzw** [comment]
What do you mean by "everything is outdated"? There is no API change recently.

**Comment by elig0n** [comment]
There is with the TTS at least. Even the URL changed, you can see my PR for comparison.

**Comment by zhouwangzw** [comment]
The example here is for Speech-To-Text, but not covering Text-To-Speech.  You can find TTS examples here https://github.com/Azure-Samples/Cognitive-Speech-TTS.
